name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH access
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            # Install Node.js if not present
            if ! command -v node &> /dev/null || ! command -v npm &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            # Install PM2 globally if missing
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi

            # Navigate to app and deploy
            cd /var/myproject/aws-backend
            git pull origin main
            npm install
            pm2 restart aws-backend || pm2 start index.js --name aws-backend
          EOF
